import { portableLightingSolutionsFaqs } from "@/lib/solution-faqs"

export const portableLightingSolutionsDefaults = {
  title: "Portable Lighting Solutions", slug: "/portable-lighting-solutions",
  hero: { title: "Portable Lighting Solutions", homeLabel: "Home", homeHref: "/", image: { src: "/portable-lighting/hero.png", alt: "Portable lighting solutions" } },
  overview: { title: "Portable Lighting Solutions for Safe & Reliable Operations", description: "Engineered for high visibility and rapid deployment, our portable lighting systems ensure safe aviation operations in remote, temporary, and emergency environments without the need for fixed infrastructure", buttonText: "Request a Quote", buttonHref: "/contact", image: { src: "/portable-lighting/specification.png", alt: "Portable lighting specifications" } },
  performance: { heading: "Engineered for Performance & Reliability", description: "", features: [
    { title: "Self-Powered Operation", description: "Integrated rechargeable battery system enables independent operation without external power sources.", image: { src: "/portable-lighting/1.png", alt: "Self-powered operation" } },
    { title: "Advanced LED", description: "Ultra-bright LED lighting ensures maximum visibility while reducing power consumption and maintenance.", image: { src: "/portable-lighting/2.png", alt: "Advanced LED lighting" } },
    { title: "Rugged Construction", description: "Built with durable materials and sealed construction (IP-rated) to withstand harsh environmental conditions.", image: { src: "/portable-lighting/3.png", alt: "Rugged portable light construction" } },
    { title: "Portable & Easy to Deploy", description: "Lightweight design with integrated handles allows quick installation, relocation, and setup.", image: { src: "/portable-lighting/4.png", alt: "Portable lighting deployment" } },
  ] },
  reliability: { heading: "Reliable Lighting Where You Need It Most", image: { src: "/portable-lighting/specs.png", alt: "Portable Lighting Specifications" }, paragraphs: ["Cranton portable lighting solutions are designed to provide dependable illumination for aviation operations where traditional power sources are unavailable or impractical. Built with advanced LED technology and integrated power systems, these lights deliver consistent performance in demanding conditions.", "Ideal for temporary helipads, emergency response, and remote operations, our systems ensure safe landing, take-off, and ground movement—anytime, anywhere."], points: [{ title: "Enables safe night and low-visibility operations" }, { title: "Eliminates dependency on fixed power infrastructure" }, { title: "Supports rapid deployment in emergency situations" }, { title: "Ensures operational continuity in remote locations" }] },
  capabilities: { heading: "Designed for Real-World Aviation Needs", description: "Our portable lighting systems go beyond basic illumination by offering advanced control and operational features.", steps: [
    { id: "01", title: "Wireless Remote Control", description: "Operate and manage lighting systems remotely, enabling efficient control from a safe distance.", image: { src: "/portable-lighting/step1.png", alt: "Wireless remote control" } },
    { id: "02", title: "Air-to-Ground Communication Control", description: "Optional integration allows direct control between ground systems and aircraft for enhanced coordination.", image: { src: "/portable-lighting/step2.png", alt: "Air-to-ground communication control" } },
    { id: "03", title: "Multiple Color Configurations", description: "Supports various color options to meet different aviation lighting requirements and operational needs.", image: { src: "/portable-lighting/step3.png", alt: "Multiple lighting color configurations" } },
    { id: "04", title: "Extended Operational Runtime", description: "Designed for long-lasting performance, ensuring continuous operation.", image: { src: "/portable-lighting/step4.png", alt: "Extended operational runtime" } },
  ] },
  industries: { badge: "", heading: "Where It’s Used", items: [
    { name: "Temporary Helipads & Vertipads", image: { src: "/portable-lighting/img1.png", alt: "Temporary helipads and vertipads" } }, { name: "Remote & Off-Grid Locations", image: { src: "/portable-lighting/img2.png", alt: "Remote and off-grid locations" } }, { name: "Airfield & Taxiway Lighting", image: { src: "/portable-lighting/img3.png", alt: "Airfield and taxiway lighting" } }, { name: "Disaster Response & Rapid Deployment", image: { src: "/portable-lighting/img4.png", alt: "Disaster response and rapid deployment" } }, { name: "Emergency & Medical Evacuation Operations", image: { src: "/portable-lighting/img5.png", alt: "Emergency and medical evacuation operations" } },
  ] },
  faqs: { heading: "Frequently Asked Questions", description: "", showNumbers: true, assistanceHeading: "Need Help ?", assistanceDescription: "Need reliable solutions or urgent support? Get in touch with our expert team today.", phone: "+44 191 640 75 03", email: "info@crantonelectric.com", image: { src: "/faqs/4.png", alt: "Portable lighting support" }, items: portableLightingSolutionsFaqs },
  cta: { heading: "Need a Portable Helipad Solution?", description: "Tell us about your project requirements and our experts will help you design the right solution for your operational needs.", buttonText: "Request a Quote", buttonHref: "/contact" },
} as const
