import type { StructureResolver } from "sanity/structure"
const pages = [
  ["Home", "page-home"], ["About Us", "page-about"], ["Contact Us", "page-contact"],
  ["Portable Helipads & Vertipads", "page-portable-helipads-and-vertipads"],
  ["Portable Lighting Solutions", "page-portable-lighting-solutions"],
] as const
const safeId = (id: string) => id.replace(/[^a-zA-Z0-9_-]/g, "-")
export const structure: StructureResolver = (S) => S.list().title("Cranton Pages").items([
  S.listItem().title("Header / Navbar").id("header-default").child(S.document().schemaType("header").documentId("header-default").title("Header / Navbar")),
  S.listItem().title("Footer").id("footer-default").child(S.document().schemaType("footer").documentId("footer-default").title("Footer")),
  S.divider(),
  S.listItem().title("Home").id("home-page").child(S.document().schemaType("homePage").documentId("home-page").title("Home Page")), S.listItem().title("About Us").id("about-page").child(S.document().schemaType("aboutPage").documentId("about-page").title("About Us Page")), S.listItem().title("Contact Us").id("contact-page").child(S.document().schemaType("contactPage").documentId("contact-page").title("Contact Us Page")), S.listItem().title("Heliports & Vertiports Lighting Solutions").id("lighting-solutions-page").child(S.document().schemaType("lightingSolutionsPage").documentId("heliports-vertiports-lighting-solutions-page").title("Heliports & Vertiports Lighting Solutions")), S.listItem().title("Heliports & Vertiports Solutions").id("heliports-solutions-page").child(S.document().schemaType("heliportsSolutionsPage").documentId("heliports-vertiports-solutions-page").title("Heliports & Vertiports Solutions")), S.listItem().title("Modular Floating Solutions").id("modular-floating-solutions-page").child(S.document().schemaType("modularFloatingSolutionsPage").documentId("modular-floating-solutions-page").title("Modular Floating Solutions")), S.listItem().title("Obstruction Lighting Solutions").id("obstruction-lighting-solutions-page").child(S.document().schemaType("obstructionLightingPage").documentId("obstruction-lighting-solutions-page").title("Obstruction Lighting Solutions")), S.listItem().title("Portable Helipads & Vertipads").id("portable-helipads-vertipads-page").child(S.document().schemaType("portableHelipadsVertipadsPage").documentId("portable-helipads-vertipads-page").title("Portable Helipads & Vertipads")), S.listItem().title("Portable Lighting Solutions").id("portable-lighting-solutions-page").child(S.document().schemaType("portableLightingSolutionsPage").documentId("portable-lighting-solutions-page").title("Portable Lighting Solutions")), ...pages.filter(([title]) => !["Home", "About Us", "Contact Us", "Portable Helipads & Vertipads", "Portable Lighting Solutions"].includes(title)).map(([title, id]) => S.listItem().title(title).id(safeId(id)).child(S.document().schemaType("sitePage").documentId(safeId(id)).title(title))),
])
