import { defineField, defineType } from "sanity"
import { imageWithAlt } from "./shared"
const paragraphFields = [defineField({ name: "paragraphs", title: "Paragraphs", type: "array", of: [{ type: "text" }] }), imageWithAlt("image", "Image")]
const cardFields = [defineField({ name: "title", title: "Title", type: "string" }), defineField({ name: "titleSource", title: "Original title", type: "string", readOnly: true, hidden: true }), defineField({ name: "description", title: "Description", type: "text" }), defineField({ name: "descriptionSource", title: "Original description", type: "text", readOnly: true, hidden: true }), defineField({ name: "imageSource", title: "Original image path", type: "string", readOnly: true, hidden: true }), defineField({ name: "image", title: "Image / icon", type: "image", options: { hotspot: true } })]
const cards = (title: string) => defineField({ name: "cards", title, type: "array", of: [{ type: "object", fields: cardFields, preview: { select: { title: "title", subtitle: "description" }, prepare: (v) => ({ title: v.title || "Card", subtitle: v.description || "" }) } }] })
export const aboutType = defineType({
  name: "aboutPage", title: "About Us Page", type: "document",
  fields: [
    defineField({ name: "heroSection", title: "Hero Section", type: "object", fields: [defineField({ name: "heading", title: "Main heading", type: "string" }), defineField({ name: "backgroundImage", title: "Background image", type: "image", options: { hotspot: true } }), defineField({ name: "breadcrumbHome", title: "Breadcrumb home label", type: "string" }), defineField({ name: "breadcrumbHomeHref", title: "Breadcrumb home link", type: "string" })] }),
    defineField({ name: "aboutCrantonSection", title: "About Cranton Section", type: "object", fields: [defineField({ name: "heading", title: "Heading", type: "string" }), ...paragraphFields] }),
    defineField({ name: "ourStorySection", title: "Our Story Section", type: "object", fields: [defineField({ name: "heading", title: "Heading", type: "string" }), ...paragraphFields] }),
    defineField({ name: "whatWeDoSection", title: "What We Do Section", type: "object", fields: [defineField({ name: "heading", title: "Heading", type: "string" }), defineField({ name: "description", title: "Description", type: "text" }), cards("Feature cards")] }),
    defineField({ name: "whyChooseSection", title: "Why Choose Us Section", type: "object", fields: [defineField({ name: "heading", title: "Heading", type: "string" }), defineField({ name: "paragraphs", title: "Paragraphs", type: "array", of: [{ type: "text" }] }), defineField({ name: "description", title: "Description", type: "text" }), defineField({ name: "missionHeading", title: "Mission heading", type: "string" }), defineField({ name: "missionDescription", title: "Mission description", type: "text" }), defineField({ name: "visionHeading", title: "Vision heading", type: "string" }), defineField({ name: "visionDescription", title: "Vision description", type: "text" }), imageWithAlt("image", "Image"), cards("Feature cards")] }),
    defineField({ name: "valuesSection", title: "Values Section", type: "object", fields: [defineField({ name: "heading", title: "Heading", type: "string" }), cards("Value cards")] }),
    defineField({ name: "testimonialsSection", title: "Testimonials Section", type: "object", fields: [defineField({ name: "heading", title: "Heading", type: "string" }), defineField({ name: "description", title: "Description", type: "text" }), cards("Testimonials")] }),
    defineField({ name: "ctaSection", title: "CTA Section", type: "object", fields: [defineField({ name: "heading", title: "Heading", type: "string" }), defineField({ name: "description", title: "Description", type: "text" }), defineField({ name: "buttonText", title: "Button text", type: "string" }), defineField({ name: "buttonHref", title: "Button link", type: "string" })] }),
    defineField({ name: "seoTitle", title: "SEO title", type: "string" }), defineField({ name: "seoDescription", title: "SEO description", type: "text" }),
  ],
})
