import { defineField, defineType } from "sanity"

const imageField = (name: string, title: string) => defineField({ name, title, type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "Alternative text", type: "string", validation: (Rule) => Rule.required() })] })
const pointFields = [defineField({ name: "title", title: "Feature / point", type: "string", validation: (Rule) => Rule.required() }), defineField({ name: "description", title: "Point description", type: "text", rows: 3 })]
const splitFields = (withWhy = false) => [defineField({ name: "title", title: "Section heading", type: "string" }), defineField({ name: "subtitle", title: "Section subtitle", type: "string" }), defineField({ name: "paragraphs", title: "Paragraphs", type: "array", of: [{ type: "text" }] }), defineField({ name: "keyTitle", title: "Features label", type: "string" }), defineField({ name: "points", title: "Features / points", type: "array", of: [{ type: "object", options: { collapsible: true, collapsed: false }, fields: [...pointFields] }] }), ...(withWhy ? [defineField({ name: "whyItMattersTitle", title: "Why it matters heading", type: "string" }), defineField({ name: "whyItMattersDescription", title: "Why it matters description", type: "text", rows: 3 })] : []), imageField("image", "Section image")]
const ctaFields = [defineField({ name: "buttonText", title: "Button text", type: "string" }), defineField({ name: "buttonHref", title: "Button link", type: "string" })]

export const lightingSolutionsType = defineType({
  name: "lightingSolutionsPage", title: "Heliports & Vertiports Lighting", type: "document",
  fields: [
    defineField({ name: "title", title: "Page title", type: "string", validation: (Rule) => Rule.required() }), defineField({ name: "slug", title: "Page slug", type: "string", readOnly: true }),
    defineField({ name: "hero", title: "Hero banner", type: "object", options: { collapsible: true, collapsed: false }, fields: [defineField({ name: "title", title: "Hero heading", type: "string" }), defineField({ name: "homeLabel", title: "Breadcrumb home label", type: "string" }), defineField({ name: "homeHref", title: "Breadcrumb home link", type: "string" }), imageField("image", "Hero background image")] }),
    defineField({ name: "overview", title: "Overview / introduction", type: "object", options: { collapsible: true, collapsed: false }, fields: [defineField({ name: "title", title: "Overview heading", type: "string" }), defineField({ name: "subtitle", title: "Overview subtitle", type: "string" }), defineField({ name: "paragraphs", title: "Overview paragraphs", type: "array", of: [{ type: "text" }] }), ...ctaFields, imageField("imageOne", "Overview image one"), imageField("imageTwo", "Overview image two")] }),
    defineField({ name: "ecosystem", title: "Complete lighting ecosystem", type: "object", options: { collapsible: true, collapsed: false }, fields: splitFields(false) }),
    defineField({ name: "reliability", title: "Reliability, efficiency & safety", type: "object", options: { collapsible: true, collapsed: false }, fields: [defineField({ name: "title", title: "Section heading", type: "string" }), defineField({ name: "description", title: "Section description", type: "text" }), defineField({ name: "features", title: "Reliability features", type: "array", of: [{ type: "object", options: { collapsible: true, collapsed: false }, fields: [defineField({ name: "title", title: "Feature title", type: "string" }), defineField({ name: "description", title: "Feature description", type: "text" }), imageField("image", "Feature icon")] }] })] }),
    defineField({ name: "flushMounted", title: "FATO / TLOF flush mounted lights", type: "object", options: { collapsible: true, collapsed: false }, fields: splitFields(true) }), defineField({ name: "floodlights", title: "Hooded LED floodlights", type: "object", options: { collapsible: true, collapsed: false }, fields: [...splitFields(true), defineField({ name: "reverse", title: "Reverse image position", type: "boolean" })] }), defineField({ name: "windIndicator", title: "Illuminated wind direction indicator", type: "object", options: { collapsible: true, collapsed: false }, fields: splitFields(true) }),
    defineField({ name: "urbanMobility", title: "Urban air mobility CTA", type: "object", options: { collapsible: true, collapsed: false }, fields: [defineField({ name: "title", title: "CTA heading", type: "string" }), defineField({ name: "subtitle", title: "CTA subtitle", type: "string" }), defineField({ name: "paragraphs", title: "CTA paragraphs", type: "array", of: [{ type: "text" }] }), ...ctaFields, defineField({ name: "solutions", title: "Solution points", type: "array", of: [{ type: "string" }] }), imageField("imageOne", "CTA image one"), imageField("imageTwo", "CTA image two")] }),
    defineField({ name: "faqs", title: "Frequently asked questions", type: "object", options: { collapsible: true, collapsed: false }, fields: [defineField({ name: "heading", title: "FAQ heading", type: "string" }), defineField({ name: "description", title: "FAQ description", type: "text" }), defineField({ name: "showNumbers", title: "Show question numbers", type: "boolean" }), defineField({ name: "assistanceHeading", title: "Support heading", type: "string" }), defineField({ name: "assistanceDescription", title: "Support description", type: "text" }), defineField({ name: "contactPhone", title: "Support phone", type: "string" }), defineField({ name: "contactEmail", title: "Support email", type: "string" }), imageField("image", "FAQ support image"), defineField({ name: "items", title: "Questions and answers", type: "array", of: [{ type: "object", options: { collapsible: true, collapsed: false }, fields: [defineField({ name: "question", title: "Question", type: "string" }), defineField({ name: "answer", title: "Answer", type: "text", rows: 4 })] }] })] }),
    defineField({ name: "seoTitle", title: "SEO title", type: "string" }),
    defineField({ name: "seoDescription", title: "SEO description", type: "text" }),
  ],
})
