import { defineField, defineType } from "sanity"
const image = (name: string, title: string) => defineField({ name, title, type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "Alternative text", type: "string" })] })
const options = { collapsible: true, collapsed: false }
const split = [defineField({ name: "id", title: "Section anchor ID", type: "string" }), defineField({ name: "title", title: "Section heading", type: "string" }), defineField({ name: "model", title: "Section subtitle", type: "string" }), defineField({ name: "description", title: "Section description", type: "text" }), defineField({ name: "features", title: "Feature points", type: "array", of: [{ type: "string" }] }), image("image", "Section image"), defineField({ name: "imageAlt", title: "Image alternative text", type: "string" })]
export const obstructionLightingType = defineType({ name: "obstructionLightingPage", title: "Obstruction Lighting Solutions", type: "document", fields: [
  defineField({ name: "title", title: "Page title", type: "string" }), defineField({ name: "slug", title: "Route path", type: "string", readOnly: true }),
  defineField({ name: "hero", title: "Hero banner", type: "object", options, fields: [defineField({ name: "title", title: "Hero heading", type: "string" }), defineField({ name: "homeLabel", title: "Breadcrumb home label", type: "string" }), defineField({ name: "homeHref", title: "Breadcrumb home link", type: "string" }), image("image", "Hero background image")] }),
  defineField({ name: "overview", title: "Overview", type: "object", options, fields: [defineField({ name: "title", title: "Overview heading", type: "string" }), defineField({ name: "description", title: "Overview description", type: "text" }), defineField({ name: "buttonText", title: "Button text", type: "string" }), defineField({ name: "buttonHref", title: "Button link", type: "string" }), image("image", "Overview image")] }),
  defineField({ name: "performance", title: "Performance and reliability cards", type: "object", options, fields: [defineField({ name: "heading", title: "Section heading", type: "string" }), defineField({ name: "description", title: "Section description", type: "text" }), defineField({ name: "features", title: "Performance cards", type: "array", of: [{ type: "object", options, fields: [defineField({ name: "title", title: "Card title", type: "string" }), defineField({ name: "description", title: "Card description", type: "text" }), image("image", "Card icon")] }] })] }),
  defineField({ name: "lowMedium", title: "Low and medium intensity lights", type: "object", options, fields: [defineField({ name: "background", title: "Background", type: "string", options: { list: ["white", "dark"] } }), defineField({ name: "sections", title: "Lighting sections", type: "array", of: [{ type: "object", options, fields: split }] })] }),
  defineField({ name: "highSolar", title: "High intensity and solar lights", type: "object", options, fields: [defineField({ name: "background", title: "Background", type: "string", options: { list: ["white", "dark"] } }), defineField({ name: "sections", title: "Lighting sections", type: "array", of: [{ type: "object", options, fields: split }] })] }),
  defineField({ name: "led", title: "LED obstruction lighting systems", type: "object", options, fields: [defineField({ name: "title", title: "Section heading", type: "string" }), defineField({ name: "model", title: "Section subtitle", type: "string" }), defineField({ name: "description", title: "Section description", type: "text" }), defineField({ name: "features", title: "Feature points", type: "array", of: [{ type: "string" }] }), image("image", "Section image"), defineField({ name: "imageAlt", title: "Image alternative text", type: "string" })] }),
  defineField({ name: "installation", title: "Reliability and compliance process", type: "object", options, fields: [defineField({ name: "title", title: "Section heading", type: "string" }), defineField({ name: "description", title: "Section description", type: "text" }), defineField({ name: "steps", title: "Process steps", type: "array", of: [{ type: "object", options, fields: [defineField({ name: "id", title: "Step number", type: "string" }), defineField({ name: "title", title: "Step title", type: "string" }), defineField({ name: "description", title: "Step description", type: "text" }), image("image", "Step image")] }] })] }),
  defineField({ name: "industries", title: "Where it's used", type: "object", options, fields: [defineField({ name: "badge", title: "Badge", type: "string" }), defineField({ name: "heading", title: "Section heading", type: "string" }), defineField({ name: "items", title: "Industries", type: "array", of: [{ type: "object", options, fields: [defineField({ name: "name", title: "Industry name", type: "string" }), image("image", "Industry image")] }] })] }),
  defineField({ name: "faqs", title: "Frequently asked questions", type: "object", options, fields: [defineField({ name: "heading", title: "FAQ heading", type: "string" }), defineField({ name: "description", title: "FAQ description", type: "text" }), defineField({ name: "showNumbers", title: "Show question numbers", type: "boolean" }), defineField({ name: "assistanceHeading", title: "Support heading", type: "string" }), defineField({ name: "assistanceDescription", title: "Support description", type: "text" }), defineField({ name: "phone", title: "Support phone", type: "string" }), defineField({ name: "email", title: "Support email", type: "string" }), image("image", "FAQ image"), defineField({ name: "items", title: "Questions and answers", type: "array", of: [{ type: "object", options, fields: [defineField({ name: "question", title: "Question", type: "string" }), defineField({ name: "answer", title: "Answer", type: "text" })] }] })] }),
  defineField({ name: "cta", title: "Final call to action", type: "object", options, fields: [defineField({ name: "heading", title: "CTA heading", type: "string" }), defineField({ name: "description", title: "CTA description", type: "text" }), defineField({ name: "buttonText", title: "Button text", type: "string" }), defineField({ name: "buttonHref", title: "Button link", type: "string" })] }),
  defineField({ name: "seoTitle", title: "SEO title", type: "string" }), defineField({ name: "seoDescription", title: "SEO description", type: "text" }),
] })
